service: referencing
frameworkVersion: '3'
plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  iam:
    role: arn:aws:iam::489034307864:role/serverless-reference-dynamo-testing

layers:
  services:
    path: services/

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
    layers:
      # - !Ref ServicesLambdaLayer
      - arn:aws:lambda:${self:provider.region}:${aws:accountId}:layer:services:6
