service: layers-test

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

layers:
  DependenciesNodeTest:
    path: middy
    description: 'middy dependencies'

resources:
  Outputs:
    ArnLayerNodeTest:
      Value: !Ref DependenciesNodeTestLambdaLayer
      Export:
        Name: middyDependencie
